### ISSUE TITLE
HiDPI support

### ISSUE THREAD

**Issue by chuchana** [borodust/bodge-ui#9]
There seems to be a problem with HiDPI support.

The example `(bodge-ui.example:run)` looks like this:
<img width="1712" alt="1680x1050x2" src="https://user-images.githubusercontent.com/3253908/57585208-1f1f7980-74e5-11e9-9629-8a1bcd10251c.png">

When I switch to the non-retina version of the same resolution, it looks like this:
![1680x1050](https://user-images.githubusercontent.com/3253908/57585206-1f1f7980-74e5-11e9-8a67-5bc70914de22.png)

The window is scaled 4x instead of 2x while the content stays the same size (400x400).

**Comment by borodust** [comment]
`bodge-ui` itself doesn't know anything about underlying system - programmer would need to manage canvas resolution (her-)himself - meaning example should be augmented to handle HiDPI displays. Instead, [`bodge-ui-window`](https://github.com/borodust/bodge-ui-window) tries to solve that problem (HiDPI support), but Retina is [still broken](https://github.com/borodust/bodge-host/issues/1) there because I don't have access to Retina-powered MacOS machine (linux and windows HiDPI support is ok though). 

Ping me in #cl-bodge IRC channel at freenode.net or directly with a private message and we can try to fix the problem present in `bodge-ui-window`.

**Comment by chuchana** [comment]
There's `Quartz Debug` in the `Additional Tools for XCode` (formerly `Graphics Tools for XCode`) which lets you simulate a retina screen on a regular one:  https://developer.apple.com/download/more/

**Comment by borodust** [comment]
Oh, thank you! I'll keep that in mind.
